### ISSUE TITLE
OCP 4.6.1 rootfs hash mismatch

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#174] opened 2020-11-06 18:04 UTC
I see you default to 4.6.1 now and since then I'm getting a rootfs hash mismatch issue. Is there something I need to do on my end and if so please point me to the docs.  I assumed your ansible tasks would take care of this and I could go back to not worrying about OCP in our CI.  Did I miss a notification somewhere?
![image](https://user-images.githubusercontent.com/37637605/98399045-d9873280-202f-11eb-98a7-c7fe93cace87.png)

**Comment by bassplay3r** [comment] 2020-11-06 18:17
TASK [Delete OCP4 files, if requested, to download again] **********************
skipping: [localhost] => (item=/usr/local/src/openshift-client-linux.tar.gz)
skipping: [localhost] => (item=/usr/local/src/openshift-install-linux.tar.gz)
skipping: [localhost] => (item=/var/www/html/install/bios.raw.gz)
skipping: [localhost] => (item=/var/www/html/install/rootfs.img)
skipping: [localhost] => (item=/var/lib/tftpboot/rhcos/initramfs.img)
skipping: [localhost] => (item=/var/lib/tftpboot/rhcos/kernel)

Set this to true?
https://github.com/RedHatOfficial/ocp4-helpernode/blob/9838fbef0bd5f9bf54d781abc41ebae9693d3fbe/vars/main.yml#L5

**Comment by bassplay3r** [comment] 2020-11-06 18:31
Changing it to true shows 
TASK [Delete OCP4 files, if requested, to download again] ***********************************
changed: [localhost] => (item=/usr/local/src/openshift-client-linux.tar.gz)
changed: [localhost] => (item=/usr/local/src/openshift-install-linux.tar.gz)
changed: [localhost] => (item=/var/www/html/install/bios.raw.gz)
ok: [localhost] => (item=/var/www/html/install/rootfs.img)
changed: [localhost] => (item=/var/lib/tftpboot/rhcos/initramfs.img)
changed: [localhost] => (item=/var/lib/tftpboot/rhcos/kernel)

**Comment by bassplay3r** [comment] 2020-11-06 18:49
Sry not rootfs not found. Hash mismatch

**Comment by xtophd** [comment] 2020-11-06 20:11
rootfs file is not signed.  need to pass additional kernel arg.

coreos.inst.insecure=yes

I haven't looked at this project so I'm not sure where to make the adjustment, but I'll look.  I had to address this in my deployment helper so I just happen to be familiar with the needed changes.

**Comment by xtophd** [comment] 2020-11-06 20:15
> rootfs file is not signed. need to pass additional kernel arg.
> 
> coreos.inst.insecure=yes
> 
> I haven't looked at this project so I'm not sure where to make the adjustment, but I'll look. I had to address this in my deployment helper so I just happen to be familiar with the needed changes.

It's documented in the red hat upi guide.

"If you are using coreos.inst.image_url, you must also use coreos.inst.insecure. This is because the bare-metal media are not GPG-signed for OpenShift Container Platform."

**Comment by deveikis** [comment] 2020-11-06 20:16
I believe it's this part:
  - name: Downloading OCP4 installer Bios
    get_url:
      url: "{{ ocp_bios }}"
      dest: /var/www/html/install/bios.raw.gz
      mode: 0555

In previous version ocp_bios was named bios.raw.gz on httpd service destination, in 4.61 boot procedure searches for rootfs.img, but ansible playbook still copies with old name. 
I had a same issue while deploying 4.6.1

**Comment by xtophd** [comment] 2020-11-06 20:28
> I believe it's this part:
> 
> * name: Downloading OCP4 installer Bios
>   get_url:
>   url: "{{ ocp_bios }}"
>   dest: /var/www/html/install/bios.raw.gz
>   mode: 0555
> 
> In previous version ocp_bios was named bios.raw.gz on httpd service destination, in 4.61 boot procedure searches for rootfs.img, but ansible playbook still copies with old name.
> I had a same issue while deploying 4.6.1

4.6 adds an additional asset that needs to be downloaded and configured.  This is an excerpt from my config not related to this project:

  "4_6":
    name:        "rhcos"
    version:     "4.6"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.1"
    initramfs:   "rhcos-4.6.1-x86_64-live-initramfs.x86_64.img"
    rootfs:      "rhcos-4.6.1-x86_64-live-rootfs.x86_64.img"
    kernel:      "rhcos-4.6.1-x86_64-live-kernel-x86_64"
    bios:        "rhcos-4.6.1-x86_64-metal.x86_64.raw.gz"
    iso:         "rhcos-4.6.1-x86_64-live.x86_64.iso"

  "4_5":
    name:        "rhcos"
    version:     "4.5"
    url:         "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.5/4.5.2"
    initramfs:   "rhcos-4.5.2-x86_64-installer-initramfs.x86_64.img"
    kernel:      "rhcos-4.5.2-x86_64-installer-kernel-x86_64"
    bios:        "rhcos-4.5.2-x86_64-metal.x86_64.raw.gz"
    iso:         "rhcos-4.5.2-x86_64-installer.x86_64.iso"


Then you also add

    "coreos.inst.insecure=yes",
    "coreos.live.rootfs_url=http://{YOUR_URL}:{YOUR_PORT}/assets/rhcos-4.6.1-x86_64-live-rootfs.x86_64.img",

to your pxe configs.

**Comment by bassplay3r** [comment] 2020-11-06 20:35
> So besides downloading and making the rootfs available, you need to add these kernel args to your pxe configs.
I think that all happens in this projects ansible or at lease I was hoping it would

**Comment by bassplay3r** [comment] 2020-11-09 14:59
Hoping the project admins can weigh in what I need to do to get around this issue

**Comment by christianh814** [comment] 2020-11-11 20:08
So interesting, I haven't had that issue. let me run some tests but I don't think I had to do that.

**Comment by bassplay3r** [comment] 2020-11-11 20:17
FYI I'm still using CentOS7 helper

**Comment by christianh814** [comment] 2020-11-11 20:36
So I'm pass the initial install of RHCOS and it booted just fine. This is a sample of the pxe config for the worker (but they are all similar)...

```
default menu.c32   
 prompt 1
 timeout 9
 ONTIMEOUT 1
 menu title ######## PXE Boot Menu ########  
 label 1
 menu label ^1) Install Worker Node
 menu default
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.7.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/worker.ign
```
I didn't have to use `coreos.inst.insecure=yes`. Are you using the latest version of the playbook? The playbook takes into account if you're using "metal bios" vs "rootfs" and changes the config accordingly. 

I'm using CentOS 8 but I'm going to try it with CentOS 7 once this test finishes.

**Comment by bassplay3r** [comment] 2020-11-11 20:45
In my CI I clone your projects  master and use that. I'm using CentOS7 and had to change the kickstart file to have another interface so my CI system can access the helper and also the cluster.

**Comment by christianh814** [comment] 2020-11-11 21:10
So my 4.6.1 installed just fine. Going to try CentOS 7

**Comment by christianh814** [comment] 2020-11-11 22:12
Just tested on Centos 7 and it worked fine as well.

```
[root@helper ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

[root@helper ~]# cat /var/lib/tftpboot/pxelinux.cfg/01-52-54-00-82-90-00 
default menu.c32   
 prompt 1
 timeout 9
 ONTIMEOUT 1
 menu title ######## PXE Boot Menu ########  
 label 1
 menu label ^1) Install Worker Node
 menu default
 kernel rhcos/kernel
 append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.1
68.7.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/worker.ign

[root@helper ~]# oc get nodes
NAME                       STATUS   ROLES    AGE   VERSION
master0.ocp4.example.com   Ready    master   37m   v1.19.0+d59ce34
master1.ocp4.example.com   Ready    master   36m   v1.19.0+d59ce34
master2.ocp4.example.com   Ready    master   37m   v1.19.0+d59ce34
worker0.ocp4.example.com   Ready    worker   27m   v1.19.0+d59ce34
worker1.ocp4.example.com   Ready    worker   27m   v1.19.0+d59ce34
```

I'm not sure what the problem is but I can't reproduce it. =\ 

Leaving this open for now to see if someone else ran into this issue.

**Comment by myki57** [comment] 2020-11-12 00:40
Hi,
I got the same issue describe in the ticket. 

After taking a look on /var/www/html/install I saw that I didn't got rootfs downloaded by the Ansible script. 

So I downloaded manually rootfs from the mirror (https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.1/), changed the name & the permissions. 

But I got other issues : 
`coreos-livepxe-rootfs[671] : etc/coreos-live-rootfs: write failed
coreos-livepxe-rootfs[671] : rhcos-46.82 xxxxxx-metal.x86_64.raw.osmet : Write failed
 coreos-livepxe-rootfs[671] : rhcos-46.82 xxxxxx-metal4k.x86_64.raw.osmet : Write failed
 coreos-livepxe-rootfs[671] : bsdtar : Error exit delayed from previous errors
 coreos-livepxe-rootfs[671] : Could'n fetch, verify, and unpack image specified by coreos.live.rootfs_url =
Main process exited 
`

For the record I'm trying to install OpenShift on a QNAP NAS with KVM like hypervisor provided by the manufacturer.

**Comment by christianh814** [comment] 2020-11-12 00:52
Can you try again from the devel branch? There has been some changes pushed there.

**Comment by myki57** [comment] 2020-11-12 07:58
Hi,
same error here after clone devel branch and applying the ansible playbook.

Before having write failed errors I have this one : 
![Capture d’écran 2020-11-12 à 08 56 33](https://user-images.githubusercontent.com/11648026/98911621-2c943600-24c5-11eb-8110-6a4504f5cdad.png)

Don't know if it helps.

**Comment by bassplay3r** [comment] 2020-11-12 13:35
Still fails for me
```
[root@helper ocp4-helpernode]# git log --oneline | head
9838fbe Merge pull request #170 from RedHatOfficial/devel
```

Should the dest not be rootfs?
 ```
 - name: Downloading OCP4 installer Bios
    get_url:
      url: "{{ ocp_bios }}"
      dest: /var/www/html/install/bios.raw.gz
      mode: 0555
```

```
TASK [Downloading OCP4 installer Bios] *****************************************
changed: [localhost]
<snip>
PLAY RECAP *********************************************************************
localhost                  : ok=74   changed=57   unreachable=0    failed=0    skipped=62   rescued=0    ignored=0

```

rootfs is not there after playbook execution
```
[root@helper ~]# find /var/www/html/
/var/www/html/
/var/www/html/install
/var/www/html/install/bios.raw.gz
/var/www/html/ignition
/var/www/html/ignition/bootstrap.ign
/var/www/html/ignition/master.ign
/var/www/html/ignition/worker.ign
[root@helper ~]#
```

It's being added to the pxeconfig
```
[root@helper ~]# grep rootfs  /var/lib/tftpboot/pxelinux.cfg/*
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-0a-46-db: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/master.ign
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-11-41-0a: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/master.ign
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-21-e6-07: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/master.ign
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-4f-0f-9a: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/bootstrap.ign
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-b9-c9-23: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/worker.ign
/var/lib/tftpboot/pxelinux.cfg/01-52-54-00-f8-b6-60: append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.168.1.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.1.77:8080/ignition/worker.ign
```

```
[root@helper ~]# cat vars.yaml
---
disk: vda
ssh_gen_key: false
helper:
  name: "helper"
  ipaddr: "192.168.1.77"
  networkifacename: "eth1"
dns:
  domain: "foo.bar.com"
  clusterid: "civpzrirmfaoupa"
  forwarder1: "10.193.159.254"
  forwarder2: "10.102.76.214"
dhcp:
  router: "192.168.1.1"
  bcast: "192.168.1.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.1.10"
  poolend: "192.168.1.30"
  ipid: "192.168.1.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.1.20"
  macaddr: "52:54:00:4f:0f:9a"
masters:
  - name: "master0"
    ipaddr: "192.168.1.21"
    macaddr: "52:54:00:11:41:0a"
  - name: "master1"
    ipaddr: "192.168.1.22"
    macaddr: "52:54:00:21:e6:07"
  - name: "master2"
    ipaddr: "192.168.1.23"
    macaddr: "52:54:00:0a:46:db"
workers:
  - name: "worker0"
    ipaddr: "192.168.1.11"
    macaddr: "52:54:00:b9:c9:23"
  - name: "worker1"
    ipaddr: "192.168.1.12"
    macaddr: "52:54:00:f8:b6:60"
[root@helper ~]#
```

**Comment by bassplay3r** [comment] 2020-11-16 14:26
@christianh814 ^^

**Comment by christianh814** [comment] 2020-11-16 14:32
Do you have a botched `vars/main.yaml` file? Or are you using one from an old install?

Also you keep showing me the section that makes me believe that you don't have the right branch.

It's supposed to look like this https://github.com/RedHatOfficial/ocp4-helpernode/blob/devel/tasks/main.yml#L126-L140

**Comment by bassplay3r** [comment] 2020-11-16 14:38
Thanks I'll verify it's using the  correct version

**Comment by myki57** [comment] 2020-11-16 14:52
Hi Christian, 
I checked and main.yaml is correct. I can confirm that the correct .img is downloaded. 

I think my issue is somewhere else. I have write issues during bootstrap install. It's maybe linked to my configuration (KVM provided by QNAP (my NAS provider)). Do you have any recommandation regarding the errors I got (Rootfs write failed).

Thanks for your help.

**Comment by christianh814** [comment] 2020-11-16 15:24
@myki57 It might be the speed of the virtual disk. I would try running IBM FIO on the NAS you're using.

https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd

**Comment by myki57** [comment] 2020-11-16 15:53
After installing Fio on one of my VM, I got 81ms on the 99,00th percentile (and 18,20 on avg). 

So my storage isn't fast enough to install bootstrap. I'm surprised. 

You think I should upgrade my NAS with SSD capabilities or I should look another reason for the issue?

**Comment by christianh814** [comment] 2020-11-16 16:00
@myki57 At a minimum, I'd update to faster disks.

**Comment by bassplay3r** [comment] 2020-11-16 16:30
I verified I'm using master but the link you referenced is devel?

[root@helper ocp4-helpernode]# git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       vars.yaml
nothing added to commit but untracked files present (use "git add" to track)
[root@helper ocp4-helpernode]# git pull
Already up-to-date.
[root@helper ocp4-helpernode]# git --no-pager log --max-count 5 --pretty=oneline --no-color --decorate=short
9838fbef0bd5f9bf54d781abc41ebae9693d3fbe (HEAD, origin/master, origin/HEAD, master) Merge pull request #170 from RedHatOfficial/devel
a34138aa4f92d09c38a0e18aa6efba6156d02dcd Merge pull request #166 from miabbott/remove_old_config
0cb17cfeaf8ea2253f93524f27d88d758888e5d3 Update main.yml
7aaf206e8be717e079b4aa4e894d386b0bb77dee Merge pull request #167 from krishvoor/master
753f9a2fbf4f4bb607d98279596a4fe34d538c6b Update quickstart-powervm.md

  - name: Delete OCP4 files, if requested, to download again
    file:
       state: absent
       path: "{{ item }}"
    with_items:
      - "/usr/local/src/openshift-client-linux.tar.gz"
      - "/usr/local/src/openshift-install-linux.tar.gz"
      - "/var/www/html/install/bios.raw.gz"
      - "/var/www/html/install/rootfs.img"
      - "/var/lib/tftpboot/rhcos/initramfs.img"
      - "/var/lib/tftpboot/rhcos/kernel"
    when: force_ocp_download

  - name: Downloading OCP4 installer Bios
    get_url:
      url: "{{ ocp_bios }}"
      dest: /var/www/html/install/bios.raw.gz
      mode: 0555
  - name: Start firewalld service
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Open up firewall ports
    firewalld:
      permanent: yes
      immediate: yes
      state: enabled
      port: "{{ item[0] }}"
    delegate_to: "{{ item[1] }}"
    run_once: true
    with_nested:
      - "{{ ports }}"

**Comment by christianh814** [comment] 2020-11-16 16:32
@bassplay3r Yes please use devel for this.this will be merged into master later this week

**Comment by myki57** [comment] 2020-11-16 16:35
Do you think that coming from 5400 RPM to 7200 RPM will be suffisent enough ?

Thanks again for your help.

**Comment by christianh814** [comment] 2020-11-16 16:42
@myki57 No, I would at least get SSDs.

**Comment by cgoguyer** [comment] 2020-11-16 16:57
@bassplay3r, I get the same issue.

It seems that /var/www/html/install/bios.raw.gz sould be /var/www/html/install/rootfs.img.
I renamed bios.raw.gz to rootfs.img and now the master nodes boot.

**Comment by bassplay3r** [comment] 2020-11-16 17:02
@cgoguyer See @christianh814 response https://github.com/RedHatOfficial/ocp4-helpernode/issues/174#issuecomment-728174518

**Comment by myki57** [comment] 2020-11-18 11:05
Hi Redbeard,
Are you sure that you are the devel branch ?
The correct changes are not yet on the main branch.

**Comment by bassplay3r** [comment] 2020-11-23 14:55
Not seeing the issue since the fix was merged to master.

**Comment by myki57** [comment] 2020-11-24 23:22
Sorry again, but after upgrading my NAS and the bootstrap VM with SSD, still got the same issue. 

Journalctl is saying : 
![Capture d’écran 2020-11-25 à 00 20 42](https://user-images.githubusercontent.com/11648026/100162559-3306b280-2eb4-11eb-8bc3-7523359b8765.png)


Any idea if it's still related to disk speed ?

**Comment by christianh814** [comment] 2020-11-24 23:27
It might be related. How are your iops? Are you connected via iscsi or nfs?

**Comment by myki57** [comment] 2020-11-25 00:14
Bear in mind that I'm using a virtualization layer on top of KVM from QNAP called virtualization center. 

VM disks are directly attached to VM (they can be attached via multiple interface types : IDE, SATA, SCSI or VirtIO). I've try everyone without much success. I created a partition on the SSD drive to host VM images.

But I've done a test with Fio and the results are pretty bad (used the config from IBM website) : 
243 IOPS
clat (usec) = avg 62,13

So I have have an issue here.

**Comment by christianh814** [comment] 2020-11-25 00:24
I would start looking more on how the storage interacts with the virtualization platform. If you're using SSDs. There's probably an issue with the connection from the platform to the storage (independent of the VMs or OpenShift).

That's why I ask if it's ISCSI or NFS. There might be network bandwidth issues.

**Comment by myki57** [comment] 2020-11-25 12:34
Ok I found out the issue. I want to kill me right now. But I didn't remember that I somehow change the amount of RAM for the bootstrap. I was at 1GB. 

Therefore it will be complicated to write anything. Thanks for your help. Much appreciated.

**Closed** 2020-11-28 20:18 UTC
Labels: bug

**Comment by xtophd** [comment] 2020-11-30 22:23
> Just tested on Centos 7 and it worked fine as well.
> 
> ```
> [root@helper ~]# cat /etc/redhat-release 
> CentOS Linux release 7.8.2003 (Core)
> 
> [root@helper ~]# cat /var/lib/tftpboot/pxelinux.cfg/01-52-54-00-82-90-00 
> default menu.c32   
>  prompt 1
>  timeout 9
>  ONTIMEOUT 1
>  menu title ######## PXE Boot Menu ########  
>  label 1
>  menu label ^1) Install Worker Node
>  menu default
>  kernel rhcos/kernel
>  append initrd=rhcos/initramfs.img nomodeset rd.neednet=1 ip=dhcp coreos.inst=yes coreos.inst.install_dev=vda  coreos.live.rootfs_url=http://192.1
> 68.7.77:8080/install/rootfs.img  coreos.inst.ignition_url=http://192.168.7.77:8080/ignition/worker.ign
> 
> [root@helper ~]# oc get nodes
> NAME                       STATUS   ROLES    AGE   VERSION
> master0.ocp4.example.com   Ready    master   37m   v1.19.0+d59ce34
> master1.ocp4.example.com   Ready    master   36m   v1.19.0+d59ce34
> master2.ocp4.example.com   Ready    master   37m   v1.19.0+d59ce34
> worker0.ocp4.example.com   Ready    worker   27m   v1.19.0+d59ce34
> worker1.ocp4.example.com   Ready    worker   27m   v1.19.0+d59ce34
> ```
> 
> I'm not sure what the problem is but I can't reproduce it. =\
> 
> Leaving this open for now to see if someone else ran into this issue.

So in my case, I use "https" URLs.  So perhaps that's the reason I needed "coreos.inst.insecure=yes" kernel flag.  Not sure, but if you have it working and passing your tests then there's nothing to see here ;-)
