### ISSUE TITLE
Playbook hangs during Open up firewall ports

### ISSUE THREAD

**Issue by yussufsh** [RedHatOfficial/ocp4-helpernode#163] opened 2020-10-14 10:17 UTC
While using HA I have noticed at random that the playbook hangs at `Open up firewall ports` task.

The reason could be because of `Start firewalld service` task just above this one. Suspecting that the ssh connection drops and the play continue infinitely. Re-running the playbook give no such issue. Perhaps because firewalld is already running on second run.

Log tail:
```
TASK [Open up firewall ports] **************************************************
changed: [192.168.25.85] => (item=67/udp) => {"ansible_loop_var": "item", "changed": true, "item": "67/udp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 67/udp to enabled"}
changed: [192.168.25.85] => (item=53/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "53/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 53/tcp to enabled"}
changed: [192.168.25.85] => (item=53/udp) => {"ansible_loop_var": "item", "changed": true, "item": "53/udp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 53/udp to enabled"}
changed: [192.168.25.85] => (item=443/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "443/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 443/tcp to enabled"}
changed: [192.168.25.85] => (item=80/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "80/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 80/tcp to enabled"}
changed: [192.168.25.85] => (item=8080/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "8080/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 8080/tcp to enabled"}
changed: [192.168.25.85] => (item=6443/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "6443/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 6443/tcp to enabled"}
changed: [192.168.25.85] => (item=6443/udp) => {"ansible_loop_var": "item", "changed": true, "item": "6443/udp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 6443/udp to enabled"}
changed: [192.168.25.85] => (item=22623/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "22623/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 22623/tcp to enabled"}
changed: [192.168.25.85] => (item=22623/udp) => {"ansible_loop_var": "item", "changed": true, "item": "22623/udp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 22623/udp to enabled"}
changed: [192.168.25.85] => (item=9000/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "9000/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 9000/tcp to enabled"}
changed: [192.168.25.85] => (item=69/udp) => {"ansible_loop_var": "item", "changed": true, "item": "69/udp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 69/udp to enabled"}
changed: [192.168.25.85] => (item=111/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "111/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 111/tcp to enabled"}
changed: [192.168.25.85] => (item=2049/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "2049/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 2049/tcp to enabled"}
changed: [192.168.25.85] => (item=20048/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "20048/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 20048/tcp to enabled"}
changed: [192.168.25.85] => (item=50825/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "50825/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 50825/tcp to enabled"}
changed: [192.168.25.85] => (item=53248/tcp) => {"ansible_loop_var": "item", "changed": true, "item": "53248/tcp", "msg": "Permanent and Non-Permanent(immediate) operation, Changed port 53248/tcp to enabled"}
.
.
<hangs here>
```

Inventory:
```
# cat ocp4-helpernode/inventory
[vmhost]
192.168.25.85 ansible_connection=ssh ansible_user=root
192.168.25.109 ansible_connection=ssh ansible_user=root
```

**Comment by Prajyot-Parab** [comment] 2020-10-14 17:54
@christianh814 

I tried all possible combinations at  `Task: Start firewalld service` using (`delegate_to`, `wait_for`,` throttle`) and I was able to reproduce the issue with all of those


I tried with the pause module and the issue is not seen/observed, or reproducible

Possible Fix-
```
diff --git a/tasks/main.yml b/tasks/main.yml
index b57b4ea..1a8f049 100644
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -129,6 +129,9 @@
       name: firewalld
       state: started
       enabled: yes
+
+  - name: wait for firewalld service to start
+    pause: seconds=10

   - name: Open up firewall ports
     firewalld:
```

Let us know your thoughts on the same and if we can go move ahead to raise PR.

**Comment by christianh814** [comment] 2020-10-14 21:23
I don't mind the `pause` there. But what if it takes more than 10 seconds to come back? 

What are your thoughts of putting a `wait_for` after the `pause`? Too much?

I guess we could just instruct people to run the playbook again.

**Comment by christianh814** [comment] 2020-10-24 21:10
Fixed in `devel`

**Closed by christianh814** 2020-10-24 21:10 UTC
