### ISSUE TITLE
failed to initialize the cluster: Cluster operator monitoring is still updating

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#31] opened 2020-04-10 17:02 UTC
Seeing install errors between CI runs of yesterday and today. Nothing has changed in my scripts but I see that OCP 4.3.8 is now being used. Moved from Centos7 to CentOS8 but no joy.

```
ssh root@10.193.156.164
helper.ciirzlitbtzrx8b.barnacle.foo.com
[root@helper ~]# tail ocp4/.openshift_install.log
time="2020-04-08T09:35:34-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.3.0: 100% complete, waiting on authentication, monitoring"
time="2020-04-08T09:35:35-07:00" level=debug msg="Cluster is initialized"
time="2020-04-08T09:35:35-07:00" level=info msg="Waiting up to 10m0s for the openshift-console route to be created..."
time="2020-04-08T09:35:35-07:00" level=debug msg="Route found in openshift-console namespace: console"
time="2020-04-08T09:35:35-07:00" level=debug msg="Route found in openshift-console namespace: downloads"
time="2020-04-08T09:35:35-07:00" level=debug msg="OpenShift console route is created"
time="2020-04-08T09:35:35-07:00" level=info msg="Install complete!"
time="2020-04-08T09:35:35-07:00" level=info msg="To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/root/ocp4/auth/kubeconfig'"
time="2020-04-08T09:35:35-07:00" level=info msg="Access the OpenShift web-console here: https://console-openshift-console.apps.ciirzlitbtzrx8b.barnacle.foo.com"
time="2020-04-08T09:35:35-07:00" level=info msg="Login to the console with user: kubeadmin, password: jua6j-ZggE9-nzyCA-2CYIa"
[root@helper ~]# oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.3.0     True        False         False      43h
cloud-credential                           4.3.0     True        False         False      44h
cluster-autoscaler                         4.3.0     True        False         False      43h
console                                    4.3.0     True        False         False      43h
dns                                        4.3.0     True        False         False      44h
image-registry                             4.3.0     True        False         False      43h
ingress                                    4.3.0     True        False         False      43h
insights                                   4.3.0     True        False         False      44h
kube-apiserver                             4.3.0     True        False         False      44h
kube-controller-manager                    4.3.0     True        False         False      44h
kube-scheduler                             4.3.0     True        False         False      44h
machine-api                                4.3.0     True        False         False      44h
machine-config                             4.3.0     True        False         False      44h
marketplace                                4.3.0     True        False         False      43h
monitoring                                 4.3.0     True        False         False      24h
network                                    4.3.0     True        False         False      44h
node-tuning                                4.3.0     True        False         False      43h
openshift-apiserver                        4.3.0     True        False         False      43h
openshift-controller-manager               4.3.0     True        False         False      44h
openshift-samples                          4.3.0     True        False         False      43h
operator-lifecycle-manager                 4.3.0     True        False         False      44h
operator-lifecycle-manager-catalog         4.3.0     True        False         False      44h
operator-lifecycle-manager-packageserver   4.3.0     True        False         False      24h
service-ca                                 4.3.0     True        False         False      44h
service-catalog-apiserver                  4.3.0     True        False         False      43h
service-catalog-controller-manager         4.3.0     True        False         False      43h
storage                                    4.3.0     True        False         False      43h

ssh root@10.193.156.165
[root@helper ~]# hostname -f

helper.cias5f8wlj0kea8.barnacle.foo.com
[root@helper ~]# tail ocp4/.openshift_install.log
time="2020-04-09T23:52:31-07:00" level=debug msg="Still waiting for the cluster to initialize: Working towards 4.3.8: 100% complete, waiting on monitoring"
time="2020-04-09T23:55:34-07:00" level=debug msg="Still waiting for the cluster to initialize: Cluster operator monitoring is still updating"
time="2020-04-09T23:58:35-07:00" level=debug msg="Still waiting for the cluster to initialize: Cluster operator monitoring is still updating"
time="2020-04-10T00:04:30-07:00" level=debug msg="Still waiting for the cluster to initialize: Cluster operator monitoring is still updating"
time="2020-04-10T00:10:36-07:00" level=debug msg="Still waiting for the cluster to initialize: Cluster operator monitoring is still updating"
time="2020-04-10T00:10:48-07:00" level=info msg="Cluster operator insights Disabled is False with : "
time="2020-04-10T00:10:48-07:00" level=info msg="Cluster operator monitoring Available is False with : "
time="2020-04-10T00:10:48-07:00" level=info msg="Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack."
time="2020-04-10T00:10:48-07:00" level=error msg="Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: running task Updating Prometheus-k8s failed: waiting for Prometheus object changes failed: waiting for Prometheus: expected 2 replicas, updated 1 and available 1"
time="2020-04-10T00:10:48-07:00" level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating"
[root@helper ~]#  oc get co
NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
authentication                             4.3.8     True        False         False      5h39m
cloud-credential                           4.3.8     True        False         False      5h55m
cluster-autoscaler                         4.3.8     True        False         False      5h46m
console                                    4.3.8     True        False         False      5h41m
dns                                        4.3.8     True        False         False      5h50m
image-registry                             4.3.8     True        False         False      5h47m
ingress                                    4.3.8     True        False         False      5h46m
insights                                   4.3.8     True        False         False      5h51m
kube-apiserver                             4.3.8     True        False         False      5h50m
kube-controller-manager                    4.3.8     True        False         False      5h48m
kube-scheduler                             4.3.8     True        False         False      5h48m
machine-api                                4.3.8     True        False         False      5h51m
machine-config                             4.3.8     True        False         False      5h50m
marketplace                                4.3.8     True        False         False      5h46m
monitoring                                           False       True          True       5h42m
network                                    4.3.8     True        False         False      5h51m
node-tuning                                4.3.8     True        False         False      5h48m
openshift-apiserver                        4.3.8     True        False         False      5h47m
openshift-controller-manager               4.3.8     True        False         False      5h49m
openshift-samples                          4.3.8     True        False         False      5h46m
operator-lifecycle-manager                 4.3.8     True        False         False      5h48m
operator-lifecycle-manager-catalog         4.3.8     True        False         False      5h48m
operator-lifecycle-manager-packageserver   4.3.8     True        False         False      5h47m
service-ca                                 4.3.8     True        False         False      5h51m
service-catalog-apiserver                  4.3.8     True        False         False      5h48m
service-catalog-controller-manager         4.3.8     True        False         False      5h48m
storage                                    4.3.8     True        False         False      5h47m
```

**Comment by christianh814** [comment] 2020-04-11 00:51
Interesting, I couldn't reproduce the problem. Can you see what `oc get pods -A | egrep  -v 'Running|Completed'` shows?

**Comment by bassplay3r** [comment] 2020-04-11 11:59
Add the above commands to the CI scripts and rerunning

**Comment by bassplay3r** [comment] 2020-04-11 20:48
Seems to be me oversubscribing my hosts.  
```

[root@helper ~]# oc get pods -A | egrep -v 'Running|Completed'
NAMESPACE                                               NAME                                                                   READY   STATUS      RESTARTS   AGE
openshift-kube-apiserver                                revision-pruner-3-master1.ci57wfxtowjrxrh.barnacle.netapp.com          0/1     OOMKilled   0          51m
openshift-monitoring                                    prometheus-k8s-1                                                       0/7     Pending     0          41m

[root@helper ~]# oc describe po openshift-monitoring
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/5 nodes are available: 2 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/5 nodes are available: 2 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.
[root@helper ~]#
```

**Comment by bassplay3r** [comment] 2020-04-11 20:54
Is there any way I can reduce the CPU requirements. Like run less masters. These are not production clusters, we are using them for functional testing.

**Comment by christianh814** [comment] 2020-04-11 23:05
You can run with only 1 master. OpenShift 4 can be installed with one master. You do this by modifying the `install-config.yaml`

The only caveat is that you have to edit the playbook so that there's only one etcd SRV record (which I think will happen as long as you have your `vars.yaml` set with one master).

Try testing by setting one master.

**Comment by bassplay3r** [comment] 2020-04-12 05:07
```
time="2020-04-11T21:33:41-07:00" level=debug msg="Still waiting for the cluster to initialize: Cluster operator monitoring is still updating"
time="2020-04-11T21:33:48-07:00" level=info msg="Cluster operator insights Disabled is False with : "
time="2020-04-11T21:33:48-07:00" level=info msg="Cluster operator monitoring Available is False with : "
time="2020-04-11T21:33:48-07:00" level=info msg="Cluster operator monitoring Progressing is True with RollOutInProgress: Rolling out the stack."
time="2020-04-11T21:33:48-07:00" level=error msg="Cluster operator monitoring Degraded is True with UpdatingPrometheusK8SFailed: Failed to rollout the stack. Error: running task Updating Prometheus-k8s failed: waiting for Prometheus object changes failed: waiting for Prometheus: expected 2 replicas, updated 1 and available 1"
time="2020-04-11T21:33:48-07:00" level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is still updating"
```

**Comment by christianh814** [comment] 2020-04-12 19:55
Are you testing with one master? If you are I gather, implicitly, that you would have "bumped" up the worker's to (at a minimum) 4 vCPUs and 8GB of RAM.

If not, you should bump those up.

**Comment by bassplay3r** [comment] 2020-04-12 21:31
OK I'm a bit confused, which seems to be my default state. :D I have one CentOS 7.7 KVM host with 14 cores(*2 hyperthreaded cores). I removed all VMs on the host and ran my process. I also bumped the CPU for the masters to 6. The first OCP4 instance worked great.  My automation creates everything  for each instance, virt-net, network, helper external IP and then seeds that info to the vars.yaml. But when my stuff does openshift-install for the 2nd instance prometheus says

```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/5 nodes are available: 2 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/5 nodes are available: 2 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.
```

How does a pod running in a vm know that the underlying host is oversubscribed?

**Comment by bassplay3r** [comment] 2020-04-12 23:24
Are you saying if I bump up the worker CPUs while having one master I would get around this error 
failed: waiting for Prometheus: expected 2 replicas, updated 1 and available 1

I took that message to be it wanted multiple masters. 

I went back and tried again with 3 masters, increasing their CPUs to 6. The first instance went well but when I added the 2nd instance Prometheus complained about lack of CPUs. Maybe it's been the workers need more CPUs all along.

**Comment by bassplay3r** [comment] 2020-04-13 02:51
The working recipe  for me seems to be
3 masters 6CPU 16G RAM
2 masters 4CPU 16G RAM
1 bootstrap 4CPU 16G RAM
1 helper 2CUP 8G RAM (We run tests from this host)

Currently running two instances, bringing up two more.

**Comment by christianh814** [comment] 2020-04-14 02:11
Glad to see it you got it working! Closing this issue as it seems to be an OpenShift capacity issue

**Closed by christianh814** 2020-04-14 02:11 UTC

**Comment by bassplay3r** [comment] 2020-04-14 14:31
Thanks for all your help with this
