### ISSUE TITLE
Error while running ansible-playbook command.

### ISSUE THREAD

**Issue by rahulsingh45-tech** [RedHatOfficial/ocp4-helpernode#54] opened 2020-05-08 14:43 UTC
Hi Team , We are getting below error while running below command. we have edited main.yml file for dhcp configuration
 ansible-playbook -e @vars.yaml /usr/ocp4-helpernode/tasks/main.yml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

PLAY [all] *****************************************************************************************************
skipping: no hosts matched

PLAY RECAP *****************************************************************************************************

**Comment by christianh814** [comment] 2020-05-08 16:23
You need to `cd` into the directory first

```
cd /usr/ocp4-helpernode
```
Then run...

```
ansible-playbook -e @vars.yaml tasks/main.yml
```

**OR**

Just provide the hostfile

```
ansible-playbook -e @vars.yaml -i /usr/ocp4-helpernode/inventory /usr/ocp4-helpernode/tasks/main.yml
```

**Comment by rahulsingh45-tech** [comment] 2020-05-11 14:44
Hi Christian,

Previous error got resolved , however getting below error now using below command.

[root@BACADGSL ocp4-helpernode]# ansible-playbook -e @vars.yaml -i /usr/ocp4-helpernode/inventory /usr/ocp4-helpernode/tasks/main.yml
 [WARNING] Ansible is being run in a world writable directory (/usr/ocp4-helpernode), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir

PLAY [all] *****************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************
The authenticity of host 'localhost (::1)' can't be established.
ECDSA key fingerprint is SHA256:NZTRF5y74Dq2Rqwey7Wa7BBVwEWsSottSfmYuD40Dsc.
ECDSA key fingerprint is MD5:dd:31:f2:bf:42:01:bc:67:27:32:da:82:d5:90:97:83.
Are you sure you want to continue connecting (yes/no)? Y
Please type 'yes' or 'no': yes
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}

PLAY RECAP *****************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by christianh814** [comment] 2020-05-11 14:53
The ansible command tells you  the error...

```
[WARNING] Ansible is being run in a world writable directory (/usr/ocp4-helpernode), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
```

**_Don't_** `chmod 777` the `/usr/ocp4-helpernode` dir. Change those permissions

**Comment by rahulsingh45-tech** [comment] 2020-05-11 15:59
Hi Christian,
It worked by passing parameter --ask-pass in same command ,  but it got failed while starting dhcp service.

[root@BACADGSL ocp4-helpernode]# ansible-playbook -e @vars.yaml -i /usr/ocp4-helpernode/inventory /usr/ocp4-helpernode/tasks/main.yml --ask-pass
 [WARNING] Ansible is being run in a world writable directory (/usr/ocp4-helpernode), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
SSH password: 

PLAY [all] *****************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************
ok: [localhost]

TASK [fail] ****************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}.
Found: item is search('{{ chars }}')
skipping: [localhost] => (item=bacadgsl.com) 
skipping: [localhost] => (item=bacadgsl) 
skipping: [localhost] => (item=bootstrap) 

TASK [fail] ****************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}.
Found: item is search('{{ chars }}')
skipping: [localhost] => (item={u'macaddr': u'00:15:5D:09:1E:8B', u'ipaddr': u'10.254.9.62', u'name': u'master0'}) 
skipping: [localhost] => (item={u'macaddr': u'00:15:5D:09:1E:8B', u'ipaddr': u'10.254.9.62', u'name': u'worker0'}) 

TASK [fail] ****************************************************************************************************
skipping: [localhost]

TASK [file] ****************************************************************************************************
ok: [localhost]

TASK [openssh_keypair] *****************************************************************************************
changed: [localhost]

TASK [lineinfile] **********************************************************************************************
changed: [localhost] => (item={u'line': u'Host *'})
changed: [localhost] => (item={u'line': u'    HostName %h.ocp4.bacadgsl.com'})
changed: [localhost] => (item={u'line': u'    User core'})
changed: [localhost] => (item={u'line': u'    IdentityFile /root/.ssh/helper_rsa'})

TASK [assert] **************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": false, 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Assertion failed"
}

TASK [set_fact] ************************************************************************************************
ok: [localhost]

TASK [set_fact] ************************************************************************************************
ok: [localhost]

TASK [set_fact] ************************************************************************************************
ok: [localhost]

TASK [set_fact] ************************************************************************************************
ok: [localhost]

TASK [set_fact] ************************************************************************************************
ok: [localhost]

TASK [set_fact] ************************************************************************************************
skipping: [localhost]

TASK [set_fact] ************************************************************************************************
skipping: [localhost]

TASK [set_fact] ************************************************************************************************
skipping: [localhost]

TASK [set_fact] ************************************************************************************************
skipping: [localhost]

TASK [Install needed packages] *********************************************************************************
changed: [localhost]

TASK [Install packages for DHCP/PXE install] *******************************************************************
changed: [localhost]

TASK [Write out dhcp file] *************************************************************************************
changed: [localhost]

TASK [Write out named file] ************************************************************************************
changed: [localhost]

TASK [Installing DNS Serialnumber generator] *******************************************************************
changed: [localhost]

TASK [Set zone serial number] **********************************************************************************
changed: [localhost]

TASK [Setting serial number as a fact] *************************************************************************
ok: [localhost]

TASK [Write out "bacadgsl.com" zone file] **********************************************************************
changed: [localhost]

TASK [Write out reverse zone file] *****************************************************************************
changed: [localhost]

TASK [Write out haproxy config file] ***************************************************************************
changed: [localhost]

TASK [Copy httpd conf file] ************************************************************************************
changed: [localhost]

TASK [Create apache directories for installing] ****************************************************************
changed: [localhost] => (item=/var/www/html/install)
changed: [localhost] => (item=/var/www/html/ignition)

TASK [Delete OCP4 files, if requested, to download again] ******************************************************
skipping: [localhost] => (item=/usr/local/src/openshift-client-linux.tar.gz) 
skipping: [localhost] => (item=/usr/local/src/openshift-install-linux.tar.gz) 
skipping: [localhost] => (item=/var/www/html/install/bios.raw.gz) 
skipping: [localhost] => (item=/var/lib/tftpboot/rhcos/initramfs.img) 
skipping: [localhost] => (item=/var/lib/tftpboot/rhcos/kernel) 

TASK [Downloading OCP4 installer Bios] *************************************************************************
changed: [localhost]

TASK [Start firewalld service] *********************************************************************************
ok: [localhost]

TASK [Open up firewall ports] **********************************************************************************
changed: [localhost] => (item=67/udp)
changed: [localhost] => (item=53/tcp)
changed: [localhost] => (item=53/udp)
changed: [localhost] => (item=443/tcp)
ok: [localhost] => (item=80/tcp)
changed: [localhost] => (item=8080/tcp)
changed: [localhost] => (item=6443/tcp)
changed: [localhost] => (item=6443/udp)
changed: [localhost] => (item=22623/tcp)
changed: [localhost] => (item=22623/udp)
changed: [localhost] => (item=9000/tcp)
changed: [localhost] => (item=69/udp)
changed: [localhost] => (item=111/tcp)
changed: [localhost] => (item=2049/tcp)
changed: [localhost] => (item=20048/tcp)
changed: [localhost] => (item=50825/tcp)
changed: [localhost] => (item=53248/tcp)

TASK [Best effort SELinux repair - DNS] ************************************************************************
changed: [localhost]

TASK [Best effort SELinux repair - Apache] *********************************************************************
changed: [localhost]

TASK [Create NFS export directory] *****************************************************************************
changed: [localhost]

TASK [Copy NFS export conf file] *******************************************************************************
changed: [localhost]

TASK [Create TFTP config] **************************************************************************************
changed: [localhost]

TASK [Create TFTP RHCOS dir] ***********************************************************************************
changed: [localhost]

TASK [SEBool allow haproxy connect any port] *******************************************************************
changed: [localhost]

TASK [Copy over files needed for TFTP] *************************************************************************
changed: [localhost]

TASK [Downloading OCP4 installer initramfs] ********************************************************************
changed: [localhost]

TASK [Downloading OCP4 installer kernel] ***********************************************************************
changed: [localhost]

TASK [Set the default tftp file] *******************************************************************************
changed: [localhost]

TASK [Set the bootstrap specific tftp file] ********************************************************************
changed: [localhost]

TASK [Set the master specific tftp files] **********************************************************************
changed: [localhost] => (item={u'macaddr': u'00:15:5d:09:1e:8b', u'ipaddr': u'10.254.9.62', u'name': u'master0'})

TASK [Set the worker specific tftp files] **********************************************************************
changed: [localhost] => (item={u'macaddr': u'00:15:5d:09:1e:8b', u'ipaddr': u'10.254.9.62', u'name': u'worker0'})

TASK [Installing TFTP Systemd helper] **************************************************************************
changed: [localhost]

TASK [Installing TFTP Systemd unit file] ***********************************************************************
changed: [localhost]

TASK [Systemd daemon reload] ***********************************************************************************
ok: [localhost]

TASK [Starting services] ***************************************************************************************
ok: [localhost] => (item=named)
changed: [localhost] => (item=haproxy)
ok: [localhost] => (item=httpd)
ok: [localhost] => (item=rpcbind)
changed: [localhost] => (item=nfs-server)
ok: [localhost] => (item=nfs-lock)
ok: [localhost] => (item=nfs-idmap)

TASK [Starting DHCP/PXE services] ******************************************************************************
failed: [localhost] (item=dhcpd) => {"ansible_loop_var": "item", "changed": false, "item": "dhcpd", "msg": "Unable to start service dhcpd: Job for dhcpd.service failed because the control process exited with error code. See \"systemctl status dhcpd.service\" and \"journalctl -xe\" for details.\n"}
changed: [localhost] => (item=tftp)
changed: [localhost] => (item=helper-tftp)

RUNNING HANDLER [restart bind] *********************************************************************************

RUNNING HANDLER [restart haproxy] ******************************************************************************

RUNNING HANDLER [restart httpd] ********************************************************************************

RUNNING HANDLER [restart dhcpd] ********************************************************************************

RUNNING HANDLER [restart tftp] *********************************************************************************

RUNNING HANDLER [restart nfs] **********************************************************************************

PLAY RECAP *****************************************************************************************************
localhost                  : ok=42   changed=32   unreachable=0    failed=1    skipped=8    rescued=1    ignored=0

**Comment by christianh814** [comment] 2020-05-11 16:14
> It worked by passing parameter --ask-pass in same command , but it got failed while starting dhcp service.

Although that worked, it failed to read the `ansible.cfg` file in that dir. Don't run it that way.

> failed: [localhost] (item=dhcpd) => {"ansible_loop_var": "item", "changed": false, "item": "dhcpd", "msg": "Unable to start service dhcpd: Job for dhcpd.service failed because the control process exited with error code. See "systemctl status dhcpd.service" and "journalctl -xe" for details.\n"}

So run `systemctl status dhcpd.service`...I'm going to guess you provided the wrong interface name in the `vars.yaml` file. How does that file look like?

**Comment by rahulsingh45-tech** [comment] 2020-05-12 14:41
Hi Christian,

In below dhcp message, it seems bad range address issue. Can you please help to set below parameters in vars.yaml file to avoid this issue.

dhcp:
  router: "10.254.8.1"
  bcast: "10.254.9.255"
  netmask: "255.255.254.0"
  poolstart: "10.254.9.50"
  poolend: "10.254.9.70"
  ipid: "10.254.9.60"
  netmaskid: "255.255.254.0"


[root@BACADGSL dhcp]# systemctl status dhcpd.service
\u25cf dhcpd.service - DHCPv4 Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/dhcpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-05-12 17:34:26 IST; 2h 34min ago
     Docs: man:dhcpd(8)
           man:dhcpd.conf(5)
  Process: 1204 ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid (code=exited, status=1/FAILURE)
 Main PID: 1204 (code=exited, status=1/FAILURE)

May 12 17:34:26 BACADGSL dhcpd[1204]: For info, please visit https://www.isc.org/software/dhcp/
May 12 17:34:26 BACADGSL dhcpd[1204]: bad range, address 10.254.8.50 not in subnet 255.255.254.0 netmask...254.0
May 12 17:34:26 BACADGSL dhcpd[1204]: 
May 12 17:34:26 BACADGSL dhcpd[1204]: This version of ISC DHCP is based on the release available
May 12 17:34:26 BACADGSL dhcpd[1204]: on ftp.isc.org.  Features have been added and other changes
May 12 17:34:26 BACADGSL dhcpd[1204]: have been made to the base software release in order to make
May 12 17:34:26 BACADGSL systemd[1]: dhcpd.service: main process exited, code=exited, status=1/FAILURE
May 12 17:34:26 BACADGSL systemd[1]: Failed to start DHCPv4 Server Daemon.
May 12 17:34:26 BACADGSL systemd[1]: Unit dhcpd.service entered failed state.
May 12 17:34:26 BACADGSL systemd[1]: dhcpd.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by christianh814** [comment] 2020-05-12 16:31
This is related to #2  ...right now, the playbook assumes a `/24`. You will need to either switch to a `/24` network space, or manually edit dhcp/dns to conform to your address space.

**Comment by christianh814** [comment] 2020-05-14 17:25
Closing since this is a duplicate of #2

**Closed by christianh814** 2020-05-14 17:25 UTC
